name: Deploy Azure Functions Microservices
on:
  push:
    paths:
      - 'services/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth-service, organization-service, ai-agent-service]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Azure Functions deploy
        run: |
          cd services/${{ matrix.service }}
          pip install -r requirements.txt -t .python_packages/lib/site-packages
          func azure functionapp publish ${{ matrix.service }} --python
